greetings:
    contains_list:
        - ['oie']
        - ['oi']
        - ['hello']
        - ['hi']
        - ['hey']
        - ['ola']
    responses:
        - "wassup"
        - "Yo man!"
        - "Howdy"
        - "sarve"
random_facts:
    contains_list:
        - ['random', 'facts']
        - ['random', 'fact']
        - ['useless', 'facts']
        - ['useless', 'fact']
    responses:
        - "It's a fact"
        - "Random fact"
        - "Is this random enough"
        - "Ok, random request, but here it goes"
        - "More randomness for you"
        - "Say no more I got u"
        - "weird flex but ok"
no_aswer:
    contains_list:
    responses:
        - "Sorry, I didn't undestand. Could you repeat please"
        - "what was that? come again please"
        - "not sure if I got it... can you say again?"
        - "wait what?"